timezone: America/Los_Angeles
highlighter: pygments
markdown: rdiscount
# permalink: /blog/:title
paginate: 2
paginate_path: "/blog/page:num/"
name: Sqor Technical Blog
description: A Technical Blog to showcase our open source materials
url: http://http://amplify-social.github.io/
excerpt_separator: ""
exclude: ['_site']